create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  row_label text,
  source text not null default 'original',
  name text not null default '',
  title text not null default '',
  phone_number text not null default '',
  category text not null default '',
  region text not null default '',
  phone_notes text not null default '',
  status text not null default '',
  notes text not null default '',
  custom_json jsonb not null default '{}'::jsonb,
  original_tags_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_fields (
  key text primary key,
  label text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists guests_set_updated_at on public.guests;
create trigger guests_set_updated_at
before update on public.guests
for each row
execute function public.set_updated_at();

create index if not exists guests_name_idx on public.guests (name);
create index if not exists guests_category_idx on public.guests (category);
create index if not exists guests_region_idx on public.guests (region);
